/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    application
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.software.amazon.awscdk.aws.cdk.lib)
    api(libs.software.constructs.constructs)
    testImplementation(libs.org.junit.jupiter.junit.jupiter)
    testImplementation("cloud.pianola:cdk-fluent-assertions:1.0.1")

}

group = "com.myorg"
version = "0.1"
description = "cdk"
java.sourceCompatibility = JavaVersion.VERSION_17

//publishing {
//    publications.create<MavenPublication>("maven") {
//        from(components["java"])
//    }
//}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

application {
    mainClass = "eu.phaf.CdkApp"
}