version: "3.5"
services:
  localstack:
    image: "localstack/localstack:latest"
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"